[formatter.nix]
command = "nixpkgs-fmt"
includes = ["*.nix"]

[formatter.shell]
command = "shfmt"
includes = ["*.sh"]

[formatter.markdown]
command = "prettier"
options = ["--parser", "markdown"]
includes = ["*.md"]
